name: AS-Software deploy 

on:
  push:
    branches:
      - deploy

permissions:
  contents: write
  id-token: write

jobs: 
  build-deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: clone repository 
        uses: actions/checkout@v4

      - name: configure NodeJs
        uses: actions/setup-node@v4
        with: 
          node-version: 20

      - name: install pnpm
        run: npm install -g pnpm 

      - name: install dependencies 
        run: pnpm install 

      - name: build proyect
        run: pnpm build 
      
      - name: config gihub pages
        uses: actions/configure-pages@v3

      - name: upload files github pages 
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
        
      - name: deploy github pages
        uses: actions/deploy-pages@v4



